language: ruby
rvm:
  - 1.9.3
before_script: ./scripts/run-tests.sh
script: "rake test"
env:
  - PUPPET_VERSION=3.4.3
branches:
  only:
    - 0.0.6
    - master
notifications:
  email: false
gemfile: Gemfile
